### ISSUE TITLE
The height of BftActuator and Bft are not ensure consistency.

### ISSUE THREAD

**Issue by rev-chaos** [cryptape/bft-rs#91]
`pub fn send_status(&mut self, status: BftMsg) -> Result<()>{
        match status {
            BftMsg::Status(s) => Ok(s),
            _ => Err(BftError::MsgTypeErr),
        }
        .and_then(|s| {
            if s.height >= self.height {
                self.height = s.height + 1;
            }
            self.sender
                .send(BftMsg::Status(s))
                .map_err(|_| BftError::SendMsgErr)
        })
}`

If the sender occurs an error, the height of BftActuator may different from Bft. Why not straightly expose Bft's height?

**Comment by KaoImin** [comment]
Because the `BftActuator` does not hold the handle of `Bft`. `BftActuctor` communicate with `Bft` by channel. The only way to get `Bft` height is to create a new channel and send a message and wait for a reply. It is a waste of resource. However, the process of `send_status` hidden danger. The `self.height = s.height + 1` should occur after `send(BftMsg::Status(s))` return `Ok(())`.
